backend:
  name: github
  repo: test-netlify-cms-2/test-netlify-cms-2.github.io
  branch: main
  base_url: https://netlify-cms-oauth-client-py.herokuapp.com
  auth_endpoint: authorize
  
site_url: https://test-netlify-cms-2.github.io
publish_mode: editorial_workflow

media_folder: "public/images"
collections:
  - name: "navigation"
    label: "Navigation"
    description: "Titles and URLs for top and bottom navigation."
    file: "_data/navigation.yml"
    fields:
      - label: "Top"
        name: "top"
        widget: "list"
        summary: "{{fields.name}} - {{fields.url}}"
        fields: 
          - { label: Icon, name: icon, widget: string }
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
      - label: "Bottom"
        name: "bottom"
        widget: "list"
        summary: "{{fields.name}} - {{fields.url}}"
        fields:
          - { label: Icon, name: icon, widget: string }
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
  - name: "page"
    label: "Pages"
    label_singular: "Page"
    folder: "collections/_pages"
    slug: "{{title}}"
    summary: '{{title}} - {{created_at}}'
    create: true
    editor:
      preview: true
    filter: { field: "layout", value: "page" }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Created At", name: "created_at", widget: "datetime" }
      - { label: "Updated At", name: "updated_at", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "post"
    label: "Posts"
    label_singular: "Post"
    description: >
      The collection for the blog posts at the website.
    folder: "collections/_posts/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: '{{title}} - {{created_at}}'
    create: true
    editor:
      preview: true
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Drafts
        field: draft
    filter: { field: "layout", value: "post" }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Created At", name: "created_at", widget: "datetime" }
      - { label: "Updated At", name: "updated_at", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        summary: '{{fields.tag}}'
        field: { label: Tag, name: tag, widget: string }
      - { label: "Content", name: "body", widget: "markdown" }
